version: "3.7"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ${JELLYFIN_LIBRARY}:/config
      - ${JELLYFIN_SERIES}:/data/tvshows
      - ${JELLYFIN_MOVIES}:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  samba:
    image: dperson/samba # no hay tag con versiones, solo latest
    restart: always
    command: '-u "pi;password" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
    stdin_open: true
    tty: true
    environment:
      - TZ=${TIMEZONE}
    ports:
      - 139:139
      - 445:445
    volumes:
      - ${MEDIA}:/media
      - ${STORAGE}/torrents:/downloads

  transmission:
    image : jaymoulin/transmission:3.00-1.6.1
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  flexget:
    image: wiserain/flexget:3.5
    volumes:
      - ./flexget:/config
      - ./flexget/custom-cont-init.d:/custom-cont-init.d
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage
    ports:
      - 5050:5050
    environment:
      - PUID=1001
      - PGID=1001
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=p3l4d0_N3RD # la puedes cambiar por la que quieras
    restart: unless-stopped
