version: "3.7"

services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ${CONFIGS}/homepage:/app/config # Make sure your local config directory exists

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=192.168.0.5
    volumes:
      - ${CONFIGS}/jellyfin:/config
      - ${SERIES}:/data/tvshows
      - ${MOVIES}:/data/movies
      - ${IMAGES}:/data/images
      - ${VIDEOS}:/data/videos
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIGS}/radarr:/config
      - ${MOVIES}:/movies #optional
      - ${DOWNLOADS}:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ${CONFIGS}/jackett:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  samba:
    image: dperson/samba 
    container_name: samba
    restart: always
    command: '-u "pi;password" -s "Storage;/Storage;yes;no;yes;all;pi;pi" -p'
    stdin_open: true
    tty: true
    environment:
      - TZ=${TIMEZONE}
      - PUID=1000
      - PGID=1000
    ports:
      - 139:139
      - 445:445
    volumes:
      - ${STORAGE}:/Storage

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8088
    volumes:
      - ${CONFIGS}/qbittorrent:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 8088:8088
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

    #command: transmission-daemon -f -g /config

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "58:53/tcp"
      - "58:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
    volumes:
      - ${CONFIGS}/pihole/etc-pihole:/etc/pihole
      - ${CONFIGS}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ${CONFIGS}/uptime_kuma:/app/data
      - /var/run/docker.sock:/app/data/docker.sock
    ports:
      - 3001:3001
    restart: unless-stopped

  rsnapshot:
    image: lscr.io/linuxserver/rsnapshot:latest
    container_name: rsnapshot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIGS}/rsnapshot:/config
      - /etc:/host/etc
      - /home/xavi:/host/home/xavi
      - ${BACKUPS}:/.snapshots
    restart: unless-stopped 

volumes:
  portainer_data:

# To Do:
  # Maddy (Mailing sv)
  # Integrate Rsnapshot with Maddy
  # DuckDNS
  # nginx + TLS all services
  

