version: "3.7"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=192.168.0.5
    volumes:
      - ${JELLYFIN_LIBRARY}:/config
      - ${JELLYFIN_SERIES}:/data/tvshows
      - ${JELLYFIN_MOVIES}:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  samba:
    image: dperson/samba 
    container_name: samba
    restart: always
    command: '-u "pi;password" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
    stdin_open: true
    tty: true
    environment:
      - TZ=${TIMEZONE}
    ports:
      - 139:139
      - 445:445
    volumes:
      - ${MEDIA}:/media
      - ${STORAGE}/torrents:/downloads
      - ${WORKDIR}:/workdir

  transmission:
    image : jaymoulin/transmission:3.00-1.6.1
    container_name: transmission
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  flexget:
    image: wiserain/flexget:3.5
    container_name: flexget
    volumes:
      - ./flexget:/config
      - ./flexget/custom-cont-init.d:/custom-cont-init.d
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage
    ports:
      - 5050:5050
    environment:
      - PUID=1001
      - PGID=1001
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=${FLEXGET_UI_PW}
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ=${TIMEZONE}
      WEBPASSWORD=${PIHOLE_WEBPASSWORD}
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

    # TO INSTALL:
      # Rsnap
      # DuckDNS